name: vitessce-python-dev
channels:
 - bioconda
 - conda-forge
dependencies:
 - python==3.8
 - jupyterlab==3.1.14
 - jupyter_server==1.11.0
 - traitlets==4.3.3
 - markupsafe==2.0.1
 - flake8==3.8.4
 - pip
 - pip:
   - build==0.1.0
