name: vitessce-python-dev
channels:
 - bioconda
 - conda-forge
dependencies:
 - python>=3.9
 - numpy>=1.21.2
 - pandas>=1.3.3
 - scipy>=1.0.0
 - anndata>=0.7.4
 - zarr>=2.5.0
 - numcodecs>=0.7.2
 - pytest>=6.2.4
 - jupyterlab>=3.2.9
 - jupyter_server>=1.13.5
 - jinja2>=3.0.3
 - traitlets>=5
 - sphinx>=4.4.0
 - nbsphinx>=0.8.8
 - pandoc>=2.14.2
 - pip
 - pip:
   - build==0.1.0
   - loompy>=3.0.6
   - nbclean==0.3.2
   - sphinx-rtd-theme==1.0.0
   - generate-tiff-offsets>=0.1.7
