name: vitessce-jupyter-dev
channels:
 - bioconda
 - conda-forge
dependencies:
 - python==3.9
 - numpy>=1.14.0
 - pandas>=1.1.2
 - anndata>=0.7.4
 - zarr>=2.5.0
 - numcodecs>=0.7.2
 - scipy>=1.0.0
 - nbsphinx>=0.7.1
 - pandoc>=2.11.3
 - pytest>=6.2.4
 - jupyterlab>=3
 - pip
 - pip:
   - build==0.1.0
   - loompy>=3.0.6
   - sphinx
   - sphinx-rtd-theme
   - nbclean>=0.3.2
   - generate-tiff-offsets>=0.1.7
