output:
- codeluppi_2018_nature_methods.image.ome.zarr
- codeluppi_2018_nature_methods.molecules.h5ad.zarr
- codeluppi_2018_nature_methods.cells.h5ad.zarr
- codeluppi_2018_nature_methods.cells.segmentations.json
