output:
- codeluppi_2018_nature_methods.cells.csv
- codeluppi_2018_nature_methods.cells.segmentations.json
- codeluppi_2018_nature_methods.cells.matrix.csv
- codeluppi_2018_nature_methods.molecules.csv
- codeluppi_2018_nature_methods.cells.h5ad.zarr
- codeluppi_2018_nature_methods.molecules.h5ad.zarr