name: vitessce-python-notebooks
channels:
 - bioconda
 - conda-forge
dependencies:
 - python==3.9
 - numpy>=1.14.0
 - pandas>=1.5.3
 - anndata==0.8.0
 - numba>=0.53.0
 - scanpy>=1.6.0
 - jupyterlab>=3
 - zarr>=2.5.0
 - boto3>=1.16.30
 - starlette==0.14.0
  # aiofiles is not explicitly referenced in our code,
  # but it is an implicit dependency of starlette==0.14.0.
  # https://github.com/encode/starlette/issues/49
  # Upgrading starlette will remove this dependency.
 - aiofiles>=0.6.0
 - pip
 - pip:
   - loompy>=3.0.6
   - scikit-misc>=0.1.3
