name: vitessce-python-demos
channels:
 - bioconda
 - conda-forge
dependencies:
 - python==3.8
 - numpy>=1.14.0
 - pandas>=1.1.2
 - anndata>=0.7.4
 - zarr>=2.5.0
 - numcodecs>=0.7.2
 - scipy
 - snakemake>=6.0
 - pyarrow>=6.0.1
 - pip
 - pip:
   - loompy>=3.0.6
   - generate-tiff-offsets>=0.1.7
   - networkx
   - obonet
   - scanpy
   - leidenalg