name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install vitessce
        run: pip install -e .[dev]
      - name: Run tests
        run: pytest
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Build docs
        run: |
          make html
          touch docs-dist/html/.nojekyll
      - name: Deploy docs to gh-pages branch
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          site-directory: docs-dist/html
      - name: Deploy package to PyPI
        continue-on-error: true
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
