name: Docs build

on: [push, pull_request]

jobs:
  docs_build:
    runs-on: ubuntu-18.04
    name: Test building docs
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install .[docs,notebook]
      - run: make html
