name: Docs build

on: [push, pull_request]

jobs:
  docs_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -e .[docs,all]
      - run: make html
