name: Test Python 3.6 (partial)

on: [push, pull_request]

jobs:
  test_python:
    runs-on: ubuntu-18.04
    name: Test Python code
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install vitessce
        run: pip install -e .[testing]
      - name: Run unittests
        working-directory: ./tests
        run: python -m unittest test_config.py
      - name: Run doctests
        working-directory: ./vitessce
        run: pytest --doctest-modules ./config.py ./repr.py
