name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Build and test
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vitessce-python-dev
          environment-file: environment.yml
          auto-activate-base: false
      - name: conda list
        run: |
          conda info
          conda list
      - name: Install vitessce
        run: pip install .[testing] .[notebook]
      - name: Run unittests
        working-directory: ./tests
        run: python -m unittest
      - name: Run doctests
        working-directory: ./vitessce
        run: pytest --doctest-modules
      - name: NPM CI
        working-directory: ./js
        run: npm ci && npm run clean
        shell: /bin/bash -e {0}
        env:
          NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build nbextension
        working-directory: ./js
        run: npm run build:nbextension
        shell: /bin/bash -e {0}
        env:
          NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build labextension
        working-directory: ./js
        run: jupyter labextension build .
